#!/usr/bin/env python

Import('env')
Import('env_modules')

env_module = env_modules.Clone()
env_module.Append(CPPPATH=[".", "raknet/Source"])

sources = Glob("*.cpp")
sources += Glob("raknet/Source/*.cpp")

# Compile as a static library
lib = env_module.Library("gd_raknet", sources)
# Add the library as a dependency of the final executable
env.Prepend(LIBS=[lib])
